name: Docker Image CI

on:
  push:
    branches: [ development ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github Checkout
      uses: actions/checkout@v2
      
    - name: Login to Digital Ocean Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITALOCEAN_PRIVATE_ACCESS_KEY }}
        password: ${{ secrets.DIGITALOCEAN_PRIVATE_ACCESS_KEY }}
    
    - name: Build Docker Container
      run: docker build -t registry.digitalocean.com/sko-server/sko-server:latest .
    
    - name: Push to Digital Ocean Registry
      run: docker push registry.digitalocean.com/sko-server/sko-server:latest
   
