name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sko-server:latest
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_PRIVATE_ACCESS_KEY }}
    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600
    - name: Tag image 
      run:
        docker tag sko-server \
        registry.digitalocean.com/sko-server/sko-server:latest
    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/sko-server/sko-server:latest
